services:
  mysql:
    image: mysql:8.4
    container_name: ticket-booking-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ticket_booking
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: root
      MYSQL_PASSWORD: WJ28@krhps
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: